### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by j18567260** [yf19970118/OPLD-Pytorch#1]
**I have trained a model,but when I test images,I have this error.**

/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/config.py:886: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = AttrDict(yaml.load(f))
INFO:utils.misc:Creating: dota-v1-1024_test
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
INFO:utils.misc:Creating: dota-v1-1024_test
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
INFO:utils.misc:The mismatch keys: ['Norm.bias', 'Norm.weight'].
INFO:utils.misc:Loading from weights: ckpts/DOTA/e2e_OPLD_R-50-FPN_1x/model_latest.pth.
/home/gen/PycharmProjects/OPLD-Pytorch-master/utils/data/structures/boxlist_ops.py:113: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  keep = ((ws >= min_size) & (hs >= min_size)).nonzero().squeeze(1)
Traceback (most recent call last):
  File "tools/test_net.py", line 55, in <module>
    main()
  File "tools/test_net.py", line 50, in main
    multi_gpu_testing=multi_gpu_testing
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 37, in run_inference
    all_results = result_getter()
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 30, in result_getter
    return test_net_on_dataset(args, multi_gpu=multi_gpu_testing)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 51, in test_net_on_dataset
    all_boxes = test_net(args)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 95, in test_net
    all_boxes = test(model, dataset, start_ind, end_ind, all_hooks)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 127, in test
    result, features = rcnn_test.im_detect_bbox(model, ims)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test.py", line 18, in im_detect_bbox
    model, ims, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test.py", line 66, in im_detect_bbox_net
    conv_features, box_results = model.box_net(ims_blob)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/modeling/model_builder.py", line 134, in box_net
    box_features, result, loss_box = self.Fast_RCNN(conv_features, proposals, targets)
  File "/home/gen/anaconda3/envs/test2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/modeling/fast_rcnn/fast_rcnn.py", line 44, in forward
    return self._forward_test(features, proposals)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/modeling/fast_rcnn/fast_rcnn.py", line 64, in _forward_test
    x = self.Head(features, proposals)
  File "/home/gen/anaconda3/envs/test2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/modeling/fast_rcnn/heads/mlp_heads.py", line 42, in forward
    x = x.view(x.size(0), -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by j18567260** [comment]
Is the test-image wrong?
