### ISSUE TITLE
Test ERROR2

### ISSUE THREAD

**Issue by j18567260** [yf19970118/OPLD-Pytorch#2]
**我使用你的预训练模型（resnet101的)进行测试，在测试结束后报如下错误**

INFO:utils.misc:[Testing][range:1-14245 of 14245][14231/14245][0.133s = 0.016s + 0.116s + 0.000s][eta: 0:00:01]
INFO:utils.misc:[Testing][range:1-14245 of 14245][14241/14245][0.133s = 0.016s + 0.116s + 0.000s][eta: 0:00:00]
INFO:utils.misc:Wrote detections to: /home/gen/PycharmProjects/OPLD-Pytorch-master/ckpts/DOTA/e2e_OPLD_R-101-FPN_1x_ms/test/detections.pkl
INFO:utils.misc:Total inference time: 1894.255s
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test_net.py", line 55, in <module>
    main()
  File "tools/test_net.py", line 50, in main
    multi_gpu_testing=multi_gpu_testing
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 37, in run_inference
    all_results = result_getter()
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 30, in result_getter
    return test_net_on_dataset(args, multi_gpu=multi_gpu_testing)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/core/test_engine.py", line 56, in test_net_on_dataset
    return evaluation(dataset, all_boxes, cfg.CLEAN_UP)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/datasets/evaluation.py", line 34, in evaluation
    pet_eval = evaluate_on_coco(dataset.coco, pet_results[iou_type], file_path, iou_type)
  File "/home/gen/PycharmProjects/OPLD-Pytorch-master/rcnn/datasets/evaluation.py", line 100, in evaluate_on_coco
    coco_dt = coco_gt.loadRes(str(json_result_file)) if coco_results else COCO()
  File "/home/gen/anaconda3/envs/test2/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 323, in loadRes
    annsImgIds = [ann['image_id'] for ann in anns]
  File "/home/gen/anaconda3/envs/test2/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 323, in <listcomp>
    annsImgIds = [ann['image_id'] for ann in anns]
TypeError: list indices must be integers or slices, not str

**Comment by j18567260** [comment]
请问该如何解决呢

**Comment by j18567260** [comment]
测试结束应该生成15个文件，而这个代码直接调用了coco测精度，这是代码错误？

**Comment by yf19970118** [comment]
For testing, this repo will generate a JSON file in the test folder and output coco precision. You need an additional script to convert the results into the DOTA official website mode.
